### ISSUE TITLE
Why is this just Pusher's library, renamed?

### ISSUE THREAD

**Issue by jasonwyatt** [eventflit/eventflit-js#1]
This seems very unethical.

**Comment by ephillipe** [comment]
Hi @jasonwyatt, 

I'm glad you asked. We had not made clear enough in the README on this subject.

We had no intention of acting unethically. We have done what we believe to be under the guidance of the MIT license.

Explaining better:
This library has been forked from (https://github.com/pusher/pusher-js). We did this because we want to change some behaviors to accommodate our own server resources. However, regarding MIT licensing, we kept the original license with this version of the library.
